forge 'forge.puppetlabs.com'

mod 'rtyler/jenkins', '1.3.0'
mod 'puppetlabs/git', '0.3.0'

mod 'puppetlabs/apt', '1.8.0'
mod 'puppetlabs/java', '1.3.0'
mod 'puppetlabs/stdlib', '4.5.1'
mod 'puppetlabs/vcsrepo', '1.2.0'

# Sample entries
# mod 'elasticsearch/elasticsearch', '0.4.0'
# mod 'elk',
#     :git => "https://github.com/timfreund/puppet-elk.git"

